"""empty message

Revision ID: 1fd996c757bc
Revises: 
Create Date: 2022-09-08 22:00:06.189970

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1fd996c757bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('check_in', 'symptoms',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('check_in', 'activities',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.add_column('journal', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('journal_page', sa.Column('date', sa.DateTime(), nullable=True))
    op.add_column('journal_page', sa.Column('body', sa.Text(), nullable=False))
    op.add_column('journal_page', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('journal_page', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journal_page', 'updated_at')
    op.drop_column('journal_page', 'created_at')
    op.drop_column('journal_page', 'body')
    op.drop_column('journal_page', 'date')
    op.drop_column('journal', 'created_at')
    op.alter_column('check_in', 'activities',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('check_in', 'symptoms',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
